---

name: Build n8n image

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.**" ]
    paths: 
    - ".github/workflows/docker.yml"
    - "**"
  pull_request:
    branches: [ "main" ]
    paths: 
    - ".github/workflows/docker.yml"
    - "**"
  release:
    types:
    - published
    - edited

jobs:
  build-docker-image:
    uses: pirogoeth/workflows/.github/workflows/docker-generic.yml@main
    with:
      output-registry: "ghcr.io"
      output-repository-path: "${{ github.repository }}"
      dockerfile-path: "./Dockerfile"
      image-tags: |
        type=raw,value=${{ github.ref_name }}
